### ISSUE TITLE
OpenStreetMap lacks visible attribution

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/who-owns-what#145]
While perusing through Rob Hawkes' excellent new [Spatial Awareness](https://www.getrevue.co/profile/maps?utm_campaign=Issue&utm_content=profileimage&utm_medium=email&utm_source=Spatial+Awareness) newsletter, I ran across the following news about [OpenStreetMap discuss terminating Facebook's right to use it](https://lists.openstreetmap.org/pipermail/talk/2019-June/082653.html?utm_campaign=Spatial%20Awareness&utm_medium=email&utm_source=Revue%20newsletter):

> After systematically failing to attribute OpenStreetMap in their maps, Facebook may be given notice of their breach of the ODbL licence. The resulting discussion on the OSM mailing list is both long and interesting, highlighting how the issue of attribution goes far beyond Facebook and isn’t something that’s easily solved.

This made me wonder if WoW attributes OSM properly.  Our map widget currently looks like this:

> ![image](https://user-images.githubusercontent.com/124687/59976062-75c0ae80-958d-11e9-84b7-c8d669bd1d8f.png)

However, that legend at the bottom-right is actually obscuring an "i" icon that, when hovered-over, would show the OSM attribution, along with a nice link to improve the map.  I disabled the display of the legend using web inspector and this is what the icon looks like when hovered over:

> ![image](https://user-images.githubusercontent.com/124687/59976073-a6a0e380-958d-11e9-929c-12532cc0ef6a.png)

That is not awesome!  It is kind of like taking content from Wikipedia without telling anyone it's from Wikipedia!!

I don't think we need to make the original Mapbox attribution visible necessarily (unless that's actually part of Mapbox's terms of use, which it very well could be) but we should at least add equivalent attribution somewhere else on the site.

**Comment by toolness** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [OpenStreetMap lacks visible attribution](https://trello.com/c/9hfAAio6/220-openstreetmap-lacks-visible-attribution)

**Comment by toolness** [comment]
OSM's [How to credit OpenStreetMap](https://www.openstreetmap.org/copyright) has more to say about this topic. It seems they prefer that the credit is given in a corner of the map, so I wonder if we should just add the credit to the bottom of the legend area.  I think it would also be neat if we added a link to help improve the map, but that is optional.

**Comment by sraby** [comment]
@toolness thank you for flagging that! I always wondered why the map had no bottom-right corner attribution like most web maps with third-party tile services... I guess there was one it was just hidden away! I will look into adding it back today
