### ISSUE TITLE
potentially incorrect information for building

### ISSUE THREAD

**Issue by aepyornis** [JustFixNYC/who-owns-what#16]
This address -- 318 SUYDAM STREET - appears to be associated with 175 other buildings, which I think may be an error.

It show two address, one being '# # # #' (possibility connected to  #15 )

![318_suydam](https://user-images.githubusercontent.com/8505044/38622150-8d74d9be-3d70-11e8-8dc0-2d40a00256dd.png)

**Comment by romeboards** [comment]
yeah, this is totally #15 - it comes from one or more #'s in `hpd_contacts` being concatenated....

![image](https://user-images.githubusercontent.com/627751/38625840-5490723a-3d79-11e8-91b5-e9b0ad65b658.png)

Would this be something that NYCDB handles? maybe converts to empty strings instead?

I have a custom agg function thats meant to handle empty strings in constructing the bisaddr:

```
-- concat_ws ignores NULL values
anyarray_uniq(anyarray_remove_null(
    array_agg(
        nullif(concat_ws(' ', businesshousenumber, businessstreetname, businessapartment, businesszip), '   ')
    )
))
as businessaddrs,
```

yeah, its a little wonky...

**Comment by aepyornis** [comment]
hmm. we could make a cleaning function to replace `nullif()` that returns null if all the strings are blank, null, or '#'

or perhaps the HPD address cleaning part of nycdb should replace '#'  with blank strings to avoiding having '#' as an address anywhere in the database in the first place.

**Comment by romeboards** [comment]
Solved by https://github.com/aepyornis/nyc-db/pull/37/files
