### ISSUE TITLE
Write up a deployment wiki page and point to it from the readme

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/who-owns-what#314]
We should base it off [the tenants2 deployment wiki page](https://github.com/justFixNYC/tenants2/wiki/Deployment).

Make sure we mention our use of nycdb-k8s-loader too.

**Comment by sraby** [comment]
@toolness I started the [Deployment Wiki Page](https://github.com/JustFixNYC/who-owns-what/wiki/Deployment). How should be go about describing deployment for the server-side?

**Comment by toolness** [comment]
Thanks!  I just added more stuff to it, does it look OK?

**Comment by toolness** [comment]
Ok Sam and I reviewed this yesterday, so I'm going to close this issue now!
