### ISSUE TITLE
Decommission either the who-owns-what or the wow-django Heroku apps

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/who-owns-what#320]
In order to switch over to the new Django+Netlify setup introduced in #306, since it involved changing DNS configuration, we actually created a new pair of Heroku apps called `wow-django` and `wow-django-dev` to host the Django-based API server, leaving the old NodeJS servers running at `who-owns-what` and `demo-whoownswhat`.  This way anyone with old DNS information would hit the old NodeJS servers while clients with the new DNS information would hit the new Django+Netlify infrastructure.

However, at some point soon, everyone should be switched over to the new setup.  The question then is whether we want to replace the old Heroku apps with the new Django version and decomission `wow-django` and `wow-django-dev`, or the other way around.  I think the main advantage of the former is that we can easily keep the Rollbar add-on we've been using without fear of it disappearing.

**Comment by sraby** [comment]
@toolness we are good to go on decommissioning
