### ISSUE TITLE
Consider removing Heap integration and anything else we're not actively using

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/who-owns-what#322]
Hmm, we just had an internal conversation at JustFix about user privacy, and while we're not sure about making FullStory opt-in just yet, it seems like it makes sense to at least stop using the third-party integrations we're not actually using, like Heap?  This should also speed up our site a bit too.

**Comment by sraby** [comment]
Yes 1000%, good idea! Let's do it

**Comment by sraby** [comment]
Fixed by #323
