### ISSUE TITLE
Consider moving all NYCHA data to the back-end

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/who-owns-what#337]
I noticed that we've got a relatively large (137k uncompressed) JSON file at `client/src/data/nycha_bbls.json` that is included in our JS bundle.  It seems to only be looked up one BBL at a time, for the current building the user is looking at, so it might make sense to move this file into the back-end, and automatically include the data in address search query results, so that clients don't need to make extra network requests to obtain it.  Doing this should result in a much smaller JS bundle.

**Comment by sraby** [comment]
Fixed by #447
