### ISSUE TITLE
We might be sending users to /en/bbl/NA/, which is invalid

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/who-owns-what#338]
It's technically possible that folks might be entering this URL manually, but it's coming from enough distinct IP's that I'm guessing we are somehow sending folks to this address, which fails because `NA` isn't a valid BBL.  Ultimately an `Error: API error from BBL page` is raised.

**Comment by sraby** [comment]
Google analytics says this is coming from "Direct Links" mostly, which is unhelpful but AFAIK this is not stemming from anything on our end.
