### ISSUE TITLE
Create manual testing instructions for WoW

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/who-owns-what#355]
Whenever we make significant changes to WoW like we did recently with our TypeScript-ification, it'd be nice to have a documented set of use cases we walked through to "kick the tires".  For example, we could make a page at `/dev/` with a list of links to [useful NYC addresses](https://github.com/justFixNYC/tenants2/wiki/Useful-NYC-addresses) that trigger various edge cases; that way manual testing could consist of just clicking every link in the list and making sure the pages look as expected.

**Comment by sraby** [comment]
@toolness would you consider this closed given your work on #373?
