### ISSUE TITLE
Coalesce our `generateBaseUrl` function and `createRouteForAddressPage` functions.

### ISSUE THREAD

**Issue by sraby** [JustFixNYC/who-owns-what#361]
We have an exported function in routes.tsx called `createRouteForAddressPage` that generates the proper route structure given the correct route params for an address page. We also have a function in the AddressPage component itself called `generateBaseUrl` that performs nearly the identical function and gets (annoyingly) passed down to child components. I'm wondering if there is a way we can eliminate the latter function using the helper instead.

**Comment by toolness** [comment]
Fixed by #390!
