### ISSUE TITLE
Switch out Geoclient for Geosearch

### ISSUE THREAD

**Issue by sraby** [JustFixNYC/who-owns-what#53]

**Comment by toolness** [comment]
Ok, I am exploring some ways to make it easier to reuse the relevant logic from the tenants app in https://github.com/JustFixNYC/tenants2/pull/442.

**Comment by toolness** [comment]
Update: I've merged the aforementioned PR and I think we can, at the very least, use the new `geo-autocomplete-base.tsx` module I made in WoW.  There's still some UI/view logic that is probably easiest to write in WoW itself.  We'll have to figure out how we want to process the TypeScript code too, whether it means adding optional TSX support to WoW or pre-compiling the TSX into JS (and perhaps publishing as an npm module) that WoW uses.
