### ISSUE TITLE
Need to account for expired HPD registrations

### ISSUE THREAD

**Issue by romeboards** [JustFixNYC/who-owns-what#58]
See example: https://whoownswhat.justfix.nyc/address/BRONX/100/CARVER%20LOOP

![image](https://user-images.githubusercontent.com/627751/47458276-2b412500-d7a7-11e8-8e16-1e0029c94f40.png)

There should probably be an indicator on the detail view that indicates if/when the registration expired. The information could definitely still be relevant though as long as there isn't a deed change or something like that. I think this might be important to have for launch / data credibility stuff...?

**Comment by sraby** [comment]
@romeboards I can look into this later today!

**Comment by romeboards** [comment]
Addressed by #58
