### ISSUE TITLE
Switch over to new Geosearch API version

### ISSUE THREAD

**Issue by TylerMatteo** [JustFixNYC/who-owns-what#666]
Hello, I'm the current team lead for the Open Source Engineering team (formerly Planning Labs) at NYC Dept of City Planning. It was brought to my attention by [@allthesignals](https://github.com/allthesignals) that JustFix uses our Geosearch API in this app. We recently released a "v2" of this API that upgrades several of the underlying open source packages that it relies on, mainly ElasticSearch and [Pelias](https://www.pelias.io/). In order to do this, we had to make some minor but breaking changes to the structure and contents of the data returned by the API. We have been supporting both the v1 and v2 versions internally while we switch over our own apps but we are planning on decommissioning the v1 version soon, as it relies on software that are past their End of Life dates for support.

With that in mind, I'm doing outreach to the external users of the API that we are aware of in hopes of avoiding any unexpected outages. We haven't identified an exact date for when we will be decommissioning v1 yet but we are hoping to do so as soon as possible and before the end of the year, at the latest.

We're still working on updating the [documentation site](https://geosearch.planninglabs.nyc/) but the "v2" version of the API is already live so you should be able to test your applications with it now and make any necessary changes. The URL and endpoints are the same as the existing version, except with "v2" instead of "v1" (so, for example, "https://geosearch.planninglabs.nyc/v2/autocomplete" instead of "https://geosearch.planninglabs.nyc/v1/autocomplete"). You should see little to no impact on the addresses returned by searches. The difference you will want to pay attention to is in the shape of the data returned. In the "properties" key of each GeoJSON feature returned, instead of having properties such as `pad_bbl` and `pad_bin`, you should see an "addendum" object containing the BBL and BIN. Those changes should be limited to fields that start with `pad_` in the v1 version so other fields, such as `postcode`, should be unchanged. Here are some Features for example (comments added):

#### Old
```
{
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -74.01054,
          40.708225
        ]
      },
      "properties": {
        "id": "3945",
        "gid": "nycpad:address:3945",
        "layer": "address",
        "source": "nycpad",
        "source_id": "3945",
        "name": "120 BROADWAY",
        "housenumber": "120",
        "street": "BROADWAY",
        "postalcode": "10271",
        "accuracy": "point",
        "country": "United States",
        "country_gid": "whosonfirst:country:85633793",
        "country_a": "USA",
        "region": "New York State",
        "region_gid": "whosonfirst:region:0",
        "region_a": "NY",
        "county": "New York County",
        "county_gid": "whosonfirst:county:061",
        "locality": "New York",
        "locality_gid": "whosonfirst:locality:0",
        "locality_a": "NYC",
        "borough": "Manhattan",
        "borough_gid": "whosonfirst:borough:1",
        "label": "120 BROADWAY, Manhattan, New York, NY, USA",
        // Some of the below fields have been removed while pad_bin and pad_bbl have been renamed and moved. Fields above 
        // this line should still exist with the same property name
        "pad_low": "104",
        "pad_high": "124",
        "pad_bin": "1001026",
        "pad_bbl": "1000477501",
        "pad_geomtype": "bin",
        "pad_orig_stname": "BROADWAY"
      }
    }
```

#### New
```
{
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -74.01052,
          40.70822
        ]
      },
      "properties": {
        "id": "3892",
        "gid": "nycpad:venue:3892",
        "layer": "venue",
        "source": "nycpad",
        "source_id": "3892",
        "country_code": "US",
        "name": "120 BROADWAY",
        "housenumber": "120",
        "street": "BROADWAY",
        "postalcode": "10271",
        "accuracy": "point",
        "country": "United States",
        "country_gid": "whosonfirst:country:85633793",
        "country_a": "USA",
        "region": "New York",
        "region_gid": "whosonfirst:region:85688543",
        "region_a": "NY",
        "county": "New York County",
        "county_gid": "whosonfirst:county:102081863",
        "locality": "New York",
        "locality_gid": "whosonfirst:locality:85977539",
        "locality_a": "NYC",
        "borough": "Manhattan",
        "borough_gid": "whosonfirst:borough:421205771",
        "neighbourhood": "Financial District",
        "neighbourhood_gid": "whosonfirst:neighbourhood:85865711",
        "label": "120 BROADWAY, New York, NY, USA",
        // Data inside of the "addendum" object replace the old "pad_" properties. So instead of "feature.properties.pad_bbl",
       //  It would be "feature.properties.addendum.pad.bbl"
        "addendum": {
          "pad": {
            "bbl": "1000477501",
            "bin": "1001026"
          }
        }
      }
    },
```

You'll notice that we removed a few fields that we believe to be unnecessary (such as `pad_low` and `pad_high`) but we're open to adding those back if we find that external users rely on them. I did a very cursory [code search](https://cs.github.com/?scopeName=All+repos&scope=&q=org%3AJustFixNYC+pad_) and it looks like JustFix only relies on `pad_bin` and `pad_bbl`.

Hopefully this is a _relatively_ straightforward migration for you all. Please reach out to me personally if there are any questions or concerns in this Issue or at tmatteo@planning.nyc.gov.

(Not sure who the most active maintainers of this are atm so tagging @romeboards and @toolness for visibility)

**Comment by rtblair** [comment]
Adding @shakao for visibility since they have been making commits in the last few months.

**Comment by shakao** [comment]
@rtblair Hey! Thanks so much for the heads up, we've seen this and will be in the process of migrating to V2 over the next few months. Do you have any dates for when V1 will be fully deprecated?

**Comment by TylerMatteo** [comment]
Hey @shakao, we are planning to fully deprecate the V1 by the end of the year. I know that timeline is a bit short by most standards but unfortunately we're being asked to get off the old version as soon as we can for security and compliance purposes. Does that sound doable for you all? If not, I'm available to discuss alternatives.

**Comment by shakao** [comment]
Sounds good, I believe this should be doable--we're prioritizing this at the moment & we'll get back to you if we run into any issues. Thanks for the heads up!

**Comment by shakao** [comment]
@TylerMatteo The changes for migrating to V2 have all been deployed, so I think we should be good! Definitely let us know if you're still seeing JustFix traffic from anywhere & we can look into it

**Comment by TylerMatteo** [comment]
@shakao Great, will do! We will be turning off the old v1 endpoints this Friday, 12/30.
