### ISSUE TITLE
Scrollbar missing in Firefox

### ISSUE THREAD

**Issue by michellemho** [JustFixNYC/who-owns-what#87]
Hi JustFixNYC! I thought this site was awesome, so I shared with some friends and one noticed that she couldn't scroll in the right-side panel for more building info. Turns out the scrollbar doesn't appear in Firefox browsers.

**Comment by toolness** [comment]
Thanks for reporting this @michellemho, and for the kind words! I just tried it out on Firefox on Windows 10 and you're right... I'm seeing an empty scrollbar, and even using the mousewheel doesn't do anything:

> ![2019-02-04_17-10-16](https://user-images.githubusercontent.com/124687/52240827-0416eb00-28a0-11e9-9396-8a30db01dc7a.png)

I'll investigate the problem in the underlying code this week and we should have a fix rolled out soon. 🤞

**Comment by toolness** [comment]
Thanks again @michellemho, I believe we've just pushed the fix to production today, so you should be able to scroll on Firefox now!  Let us know if you have any problems.

**Comment by michellemho** [comment]
It looks great!
